openapi: 3.0.3
info:
  title: "GreenBack API v1"
  description: "WebAPI for JTDI"
  contact:
    email: "doudemoethernet@fastmail.jp"
  version: "1.0.0"
servers:
  - url: "https://greenback.doudemoether.net"
    description: "v1"
tags:
  - name: "Account"
    description: "アカウント"
  - name: "Task"
    description: "タスク"
paths:
  "/account/signup":
    post:
      tags: ["Account"]
      summary: "Signup"
      description: "新規アカウントの作成"
      operationId: "signUp"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "400":
          description: "bad request"
        "500":
          description: "internal error"
  "/account/login":
    post:
      tags: ["Account"]
      summary: "Login"
      description: "ログイン"
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "400":
          description: "bad request"
        "404":
          description: "not found"
        "500":
          description: "internal error"
  "/task":
    post:
      tags: ["Task"]
      summary: "Create task"
      description: "新規タスクを作成します"
      operationId: "createTask"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task-create"
      responses:
        "200":
          description: "success"
        "500":
          description: "failed to create task"
        "400":
          description: "bad request"
    get:
      tags: ["Task"]
      summary: "get task"
      description: "タスクを取得します"
      operationId: "getTask"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task-get-array"
        "404":
          description: "not found"
        "500":
          description: "internal error"
    patch:
      tags: ["Task"]
      summary: "update task"
      description: "タスクを編集します"
      operationId: "updateTask"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task-content"
      responses:
        "200":
          description: "success"
        "400":
          description: "failed to update task"
        "500":
          description: "internal error"
  "/task/{id}":
    delete:
      tags: ["Task"]
      summary: "delete task"
      description: "タスクを削除します"
      operationId: "deleteTask"
      parameters:
        - name: "id"
          in: path
          required: true
          description: "Task id"
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "success"
        "400":
          description: "bad request"
        "404":
          description: "target task not found"
        "500":
          description: "internal error"

components:
  schemas:
    Account:
      type: object
      properties:
        userId:
          type: string
          example: "username"
        password:
          type: string
          example: "password"
    Token:
      type: object
      properties:
        token:
          type: string
          example: "aasdahbsakodjfpaoi3w40m03w4hjnvgsopru32"
        expr:
          type: number
          description: "Expiration time of the API token(unix timestamp)"
          example: 123456789123465
    Task-create:
      type: object
      properties:
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-content:
      type: object
      properties:
        id:
          type: string
          example: 45fb12a8-70a2-4535-970a-3d66b0d6f83f
          format: uuid
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-get-array:
      type: array
      items:
        $ref: "#/components/schemas/Task-content"

