openapi: 3.0.3
info:
  title: "GreenBack API v1"
  description: "WebAPI for JTDI"
  contact:
    email: "doudemoethernet@fastmail.jp"
  version: "1.0.0"
servers:
  - url: "https://greenback.doudemoethernet.workers.dev"
    description: "v1"
tags:
  - name: "Task"
    description: "タスク"
paths:
  "/task":
    post:
      tags: ["Task"]
      summary: "Create task"
      description: "新規タスクを作成します"
      operationId: "createTask"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task-create"
      responses:
        "200":
          description: "success"
        "500":
          description: "failed to create task"
        "400":
          description: "bad request"
    get:
      tags: ["Task"]
      summary: "get task"
      description: "タスクを取得します"
      operationId: "getTask"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task-get-array"
        "404":
          description: "not found"
        "500":
          description: "internal error"
    patch:
      tags: ["Task"]
      summary: "update task"
      description: "タスクを編集します"
      operationId: "updateTask"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task-content"
      responses:
        "200":
          description: "success"
        "400":
          description: "failed to update task"
        "500":
          description: "internal error"
  "/task/{id}":
    delete:
      tags: ["Task"]
      summary: "delete task"
      description: "タスクを削除します"
      operationId: "deleteTask"
      parameters:
        - name: "id"
          in: path
          required: true
          description: "Task id"
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "success"
        "400":
          description: "bad request"
        "404":
          description: "target task not found"
        "500":
          description: "internal error"

components:
  schemas:
    Task-create:
      type: object
      properties:
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-content:
      type: object
      properties:
        id:
          type: string
          example: 45fb12a8-70a2-4535-970a-3d66b0d6f83f
          format: uuid
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-get-array:
      type: array
      items:
        $ref: "#/components/schemas/Task-content"

