openapi: 3.0.3
info:
  title: "GreenBack API v1"
  description: "WebAPI for JTDI"
  contact:
    email: "doudemoethernet@fastmail.jp"
  version: "1.0.0"
servers:
  - url: "https://greenback.doudemoethernet.workers.dev"
    description: "v1"
tags:
  - name: "Task"
    description: "タスク"
paths:
  "/task":
    post:
      tags: ["Task"]
      summary: "Create task"
      description: "新規タスクを作成します"
      operationId: "createTask"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task-create"
      responses:
        "200":
          description: "success"
        "400":
          description: "failed to create task"
    get:
      tags: ["Task"]
      summary: "get task"
      description: "タスクを取得します"
      operationId: "getTask"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task-get-array"

components:
  schemas:
    Task-create:
      type: object
      properties:
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-get-content:
      type: object
      properties:
        id:
          type: string
          example: 45fb12a8-70a2-4535-970a-3d66b0d6f83f
          format: uuid
        title:
          type: string
          example: "TaskName"
        description:
          type: string
          example: "TaskDescription"
        difficulty:
          type: number
          example: 0
    Task-get-array:
      type: array
      items:
        $ref: "#/components/schemas/Task-get-content"

